apiVersion: v1
kind: Service
metadata:
  name: nodejsapp2-service
spec:
  type: NodePort
  selector:
    app: nodejsapp2
  ports:
    - protocol: TCP
      port: 3000        # Port exposed inside the cluster
      targetPort: 3000  # Port your Node.js app listens on
      nodePort: 30036   # Optional: External port on the node (range 30000–32767)
